### ISSUE TITLE
Demo for viewing selected items in a label group

### ISSUE THREAD

**Issue by terezanovotna** [patternfly/patternfly-design#918] opened 2020-09-24 13:27 UTC
In cloud.redhat., we are using a modal with table that has a lot of content. 
When 5 items are selected and I am on a different page (we have 147 pages), the user doesn't get to see what he has selected on previous pages. We would like to see a consistent solution in PF
<img width="340" alt="Screen Shot 2020-09-24 at 15 24 59" src="https://user-images.githubusercontent.com/36040135/94151015-2c3ecd80-fe7a-11ea-986f-7d232b62aca7.png">

**Use case in brief:**
As a user I want to see my what items I have already selected even though I am already browsing on other pages. 

**Possible solution:**
Show chips under or above the toolbar with the correct selection, so the user always knows what is selected. 

Here is an example how RBAC is solving this situation by @mmenestr 
![Screenshot from 2020-09-24 14-58-48](https://user-images.githubusercontent.com/36040135/94151170-60b28980-fe7a-11ea-83b8-7926f7d1a1f9.png)

**Comment by mmenestr** [comment] 2020-09-24 15:36
Also want to add that the RBAC solution is also being used in Ansible - @trahman73

**Comment by mcarrano** [comment] 2020-09-24 16:11
@terezanovotna I am fine with following the solution that @mmenestr offered if that works for you. Were you thinking that something should be integrated more with the table component? I did want to draw your attention to this issue which is currently in the queue for implementation: https://github.com/patternfly/patternfly/issues/1860 It's OpenShift's solution to a similar problem. I'm not saying that 'favoriting' items is the approach you should use, but in both cases, the problem is how to quickly scan for items that are selected. Maybe this is a good topic for cross-project discussion at the next PF design share?

**Comment by terezanovotna** [comment] 2020-09-24 16:40
@mcarrano thanks for a quick reply! 

I like the favoriting items approach - but that would not work for this use case. 

I was mostly wondering if we want to include this pattern in pf documentation so others can use it. We came across this issue in a usability test and with having this pattern in our design system, it would have been prevented.

- show n numbers selected in the UI (dropdown with numbers)
- quickly view them (using @mmenestr approach)

**Comment by mcarrano** [comment] 2020-09-24 17:49
I'm Ok with endorsing this approach in the design documentation, just not sure where that belongs. Thoughts @mmenestr ?

**Comment by mmenestr** [comment] 2020-09-24 18:07
@mcarrano @terezanovotna If we did decided to mention it in documentation, i'd include it in the table documentation as a "Way to show selections to users as they go" kind of solution!

With that being said, since this is technically not a pattern that's offered by PF, and it's just a custom solution implemented in c.rh.c, I don't know that we should include it in the design guidelines.. @terezanovotna like Matt, I thought that you wanted to propose this to be implemented as a solution by PF!

**Comment by terezanovotna** [comment] 2020-09-25 13:30
I initially wanted to have it as PF solution, but then realized there is nothing to build as it is already composed from pf components.

Love the approach of "way to show selections as they go"

**Comment by mcarrano** [comment] 2020-09-25 13:40
So can I close this out? Is there anything to do here on the PatternFly side of things?

**Comment by mmenestr** [comment] 2020-09-25 13:44
@mcarrano @terezanovotna See, I saw this more as a "demo", like primary-detail for example. Primary detail is just a "compilation" of a bunch of different components put together to create a pattern, and this would essentially be the same thing. So I feel like there could be a case for making this a PF pattern/demo. It could be a feature that people add as an option into their modal or wizard tables? What do you think? 

Also, @trahman73, not sure if you have any thoughts on this

**Comment by trahman73** [comment] 2020-09-25 13:54
@mmenestr I agree with the PF demo approach, as we are already using this pattern to show selected info in Ansible Tower and Analytics.

**Comment by mcarrano** [comment] 2020-09-25 17:38
OK. That makes sense. In that case I have renamed this to more appropriately reflect what the ask is and tagged it as a demo.

**Comment by terezanovotna** [comment] 2020-09-29 07:39
@mcarrano thanks Matt. Looking forward to seeing it in Patternfly!

**Comment by terezanovotna** [comment] 2020-10-12 09:50
having this in a demo - would help us keep consistency - https://github.com/RedHatInsights/frontend-components/pull/772

**Comment by terezanovotna** [comment] 2020-10-12 09:58
<img width="737" alt="Screen Shot 2020-10-12 at 11 58 33" src="https://user-images.githubusercontent.com/36040135/95733329-46eab200-0c82-11eb-903f-1d94d8826799.png">

**Closed** 2023-06-01 13:22 UTC
Labels: Demo
