### ISSUE TITLE
Enhancement to tree view pattern

### ISSUE THREAD

**Issue by bmignano** [patternfly/patternfly-design#1020] opened 2021-03-30 15:59 UTC
This enhancement request is related to the design mentioned in https://github.com/patternfly/patternfly-design/issues/994

We want to update the Schema explorer in OpenShift to use the [tree view](https://www.patternfly.org/v4/components/tree-view/). However, the tree view as is makes it very difficult to discern the different nodes in the tree and their respective levels. Something to note here also is that in this case we need both a node header and description, which no current tree view examples have. The following mock uses the tree view as is, with no enhancements:
![3](https://user-images.githubusercontent.com/40238481/113018356-7452eb80-914e-11eb-93a2-1d1302460708.png)

In order to better distinguish the nodes and levels, we would like to propose an enhancement to the tree view that adds horizontal separators as well as tree "branches". In addition, this design bolds the header for each node, as opposed to just those that are open.
![9](https://user-images.githubusercontent.com/40238481/113018445-93ea1400-914e-11eb-9c3a-e434473c6ec6.png)

**Comment by mcarrano** [comment] 2021-03-30 17:35
@bmignano looks like this request is a duplicate of https://github.com/patternfly/patternfly-design/issues/994. Can you consolidate these into one issue/request? It will just make it easier to track. Maybe keep this one open and close the older issue? But it would also be useful to show the Openshift mock here.

**Comment by mcarrano** [comment] 2021-04-05 18:17
@bmignano there may be some implementation issues with this, but we will get it on the roadmap to investigate more. Is there a timeframe when this is needed?

**Comment by bmignano** [comment] 2021-04-05 18:31
@mcarrano The implementation story has yet to be groomed and prioritized, so I'm not sure about a timeframe just yet, but I can certainly get back to you once I have a better idea.

**Comment by mcarrano** [comment] 2021-06-21 14:26
This has been addressed by https://github.com/patternfly/patternfly-design/issues/1043. Opened https://github.com/patternfly/patternfly/issues/4177 to track core implementation.

**Closed by mcarrano** 2021-06-21 14:26 UTC
Labels: Enhancement, OpenShift
