### ISSUE TITLE
Next/Back button position in wizards

### ISSUE THREAD

**Issue by pondrejk** [patternfly/patternfly-design#1078] opened 2021-04-09 11:39 UTC
Having read [1][2][3] I see the "primary button on left" approach has some backing, though in case of Next/Back buttons it goes against what is common in majority of interfaces and will likely produce misclicks. 

I wonder if we could reconcile the views and put the Back button above or below Next. This way primary button will still be on the left + not having those buttons on the same row will less likely mess with people's muscle memory. Something like this:

![back-img1](https://user-images.githubusercontent.com/8287578/114174470-f3a7a280-9938-11eb-8455-1461f4ff39a5.png)

[1] https://www.patternfly.org/v4/components/wizard/design-guidelines/#types-of-wizards
[2] https://medium.com/patternfly/button-placement-on-forms-aa57a81f7d
[3] https://forum.patternfly.org/t/wizard-button-placement

**Comment by mcarrano** [comment] 2022-09-19 20:23
This looks like a duplicate of #1115. Will close this.

**Closed by mcarrano** 2022-09-19 20:23 UTC
