### ISSUE TITLE
Design inconsistency with dual list selector

### ISSUE THREAD

**Issue by bmignano** [patternfly/patternfly-design#684] opened 2018-06-21 18:40 UTC
This is a design inconsistency with bulk selector pattern.

Industry standards show that users would expect the bulk selector to deselect all items when acting on a partially selected list. The [dual list selector](http://www.patternfly.org/pattern-library/forms-and-controls/dual-list-selector/) currently does the opposite and states: "When some items are selected, if the user then clicks the Select All button, all items will then be selected. Clicking again will deselect all items."

The bulk selector pattern follows industry standards. We should update the dual list selector to be consistent.

FYI @mcarrano @serenamarie125

**Comment by mcarrano** [comment] 2018-06-21 18:57
@Rohoover Can you please comment on this since you were the primary designer on Dual List Selector? Do you agree with this change?

**Comment by Rohoover** [comment] 2018-06-21 19:31
If I understand your concern correct, then I disagree. 

If only a few items are selected, then the bulk selector (which is a checkbox) is in an de-actived state (un-checked).

If you were to have a partial selection, and THEN to click the de-actived bulk selector it would cause ALL items to be selected (changing the box to checked). It would not deselect items (with no effect on the checkbox).

The behavior within the dual pane is consistent and seen within PatternFly's [tables](http://www.patternfly.org/pattern-library/content-views/table-view/#code)

If you select a few rows, and then click on the bulk selector, all items become selected. A subsequent click would deselect all. If the bulk selector is engaged (active) and then the user deselects individual items, the bulk selector checkbox is de-activated.

**Comment by serenamarie125** [comment] 2018-06-21 19:38
PatternFly's tables don't show partial selection, so i don't think it's the same.  When an item is selected in the table, the guiding checkbox is in the unselected state, which doesn't make much sense, does it?

The new proposal is in line with industry standards IMO.  If 1+ elements are selected (but not all) , the guiding checkbox shows partial selection.  Clicking a partial selected checkbox will deselect all.  Clicking an unselected checkbox will select all.

Curious to hear other's thoughts @lizsurette @beanh66 ?

**Comment by serenamarie125** [comment] 2018-06-21 19:39
@Rohoover i wonder if table/dual selector should show partial selection and update to this same model?

**Comment by Rohoover** [comment] 2018-06-21 19:51
@serenamarie125 

The tables do show a partial selection in that you can select individual rows much like in dual pane - you can select individual items. Clicking on bulk would select all. The dual pane and table bulk selector, selection functionality is the same. It's the old school way of how bulk editing is handled. The functionality being described above is new (as visible in gmail).

I'm not against a new approach. If we want to make a change to the bulk editing functionality, then I agree, we should do it universally as I think it's confusing to have two different types.

**Comment by bmignano** [comment] 2018-06-21 19:59
I actually also tend to think that it makes more sense to select all if the checkbox is clicked in a partially selected list (this just matches my mental model better as it is a bulk selector). If industry standards have changed though, maybe we should as well? I think it's also a matter of what the checkbox looks like in a partially selected list. Gmail has a - sign, indicating that clicking the box would in fact deselect all items.

Would agree though that whatever we decide to use it should definitely be universal across patterns.

**Comment by beanh66** [comment] 2018-06-21 20:17
@serenamarie125 @Rohoover Yeah, I am actually in the same boat as @bmignano. I expected that clicking the checkbox for partially selected list would select all. Agreed if industry standard says otherwise, happy to change and be consistent across PF :+1:

**Comment by lizsurette** [comment] 2018-06-21 20:37
Yeah totally agree about at the very least being consistent between PatternFly patterns :)

I don't have a strong opinion either way, so I lean towards the industry standard of "the bulk selector should deselect all items when acting on a partially selected list."

**Comment by Rohoover** [comment] 2018-06-21 20:45
Just for clarification as I’m seeing different industry standards reflected here...

This is my understanding:

Old standard - Bulk select always selects all and deselects all when all are selected. If bulk is selected, and user deselects some items, bulk checkbox is then deselected. There is no partial state.

New hotness:
The bulk selector now accommodates a partial state. This partial state will deselect all partial selections. Full bulk selection capabilities still apply.

Just want to make sure we are talking about the same functionality 😄

**Comment by beanh66** [comment] 2018-06-21 20:48
haha well summarized @Rohoover, I think that's what everyone's saying 💯

**Comment by mcarrano** [comment] 2018-06-22 13:49
I did a bit of research on this. Currently in PatternFly we use a standard HTML checkbox which only supports two states: checked and unchecked. To get an intermediate state, additional JS customization is required. This is described well in this article: https://css-tricks.com/indeterminate-checkboxes/  I confirmed this in a conversation with @matthewcarleton .

IMO, the value of the intermediate state is not enough to justify creating a new checkbox component, especially for PF 3.  I feel like the way that our current data table and dual list selector work is intuitive enough, and we should therefore follow that even if it doesn't exactly match what Google and others are doing on the web. I propose to close this out and update the Bulk Selector to only show two states: checked and unchecked with the box being unchecked whenever there is mixed selection.

**Comment by serenamarie125** [comment] 2018-06-22 13:53
@mcarrano - please be sure to comment [here](https://github.com/patternfly/angular-patternfly/pull/742) then, as a PR is up in Angular implementing the proposed design.  Thanks!

**Comment by catrobson** [comment] 2018-06-22 14:41
@mcarrano while I understand your point about the HTML/CSS not being able to support this, I'm not sure I'm following the result that we shouldn't do this in our design pattern documentation.  I thought we've talked about many behaviors only be supported at the JS layer, and this feels like an example of that where our design pattern specifies a certain behavior that can only be supported once you get into the JS layer.  In our HTML/CSS implementation in core, we might not be able to support the full pattern behaviors.

Thoughts?

**Comment by mcarrano** [comment] 2018-06-22 14:50
I thought about that, too, @catrobson .  I guess that's OK if we are comfortable with the idea that the behavior might be inconsistent across our products depending on the framework they use. 

I guess that the question I'd pose to folks is do you think supporting this mixed state provides enough value to justify the extra implementation work? IMO it didn't seem to, and to some extent complicated the interaction as evidenced by this thread. It hadn't occurred to me that the current selection behavior was a problem.

**Comment by Rohoover** [comment] 2018-06-22 15:05
I have no strong opinion on whether the work is justified but I also don't find the current selection behavior problematic.

**Comment by beanh66** [comment] 2018-06-25 14:41
@mcarrano I lean towards supporting the partial selection since (1) As a user I find it useful in Gmail and Sketch and (2) we have the Angular implementation and Design contribution to support it. I agree with @catrobson and was also thinking of it as an iterative process, where other repos may update to include this piece in the future. Could we file corresponding issues in those repos to track the work?

**Comment by matthewcarleton** [comment] 2018-06-25 15:06
just to add to what @mcarrano was saying. If we go the route of partial selection we will need custom JS work but also we will need to create a totally custom css/html implementation as well. In a default checkbox there is no partial selection available. I'm not saying this is a bad idea, but just wanted to clarify the amount of work required.

**Comment by serenamarie125** [comment] 2018-06-25 15:59
IMO we shouldn't disallow because of core not being able to support the behavior.
I suggest we take bulk selection as proposed, file associated issues to support partial selection for checkbox.

**Comment by mcarrano** [comment] 2018-07-11 14:41
I am going to close this one out for now as we agreed that partial state selection is an optional capability. We can revisit contingent on #685 to support partial selection state in Core.

**Closed by mcarrano** 2018-07-11 14:41 UTC
Labels: Bug, Consistency
