### ISSUE TITLE
Provide default state for form select

### ISSUE THREAD

**Issue by matthewcarleton** [patternfly/patternfly-design#775] opened 2019-06-05 15:47 UTC
Currently in the form select input we don't have a style for a "placeholder" text. It would be helpful if we styled the text to be different from the selected text option.

Here is a possible design solution.
<img width="909" alt="Screen Shot 2019-06-05 at 12 42 28 PM" src="https://user-images.githubusercontent.com/287880/58970366-b055d900-878f-11e9-8e84-ac6d58cb18cb.png">

```
font-style: italic;
color: #72767b; ($pf-color-black-600)
```
fyi: @kybaker @mceledonia

**Comment by bgliwa01** [comment] 2020-10-06 22:04
![pf-default_select](https://user-images.githubusercontent.com/51342070/95265035-5be8c080-07fe-11eb-8a2e-0ec01752255e.png)
@matthewcarleton @mcarrano @andybraren Here is my suggestion, please let me know your thoughts! Thanks

**Comment by mcarrano** [comment] 2020-10-07 12:52
@mceledonia @mcoker thoughts?

**Comment by mcoker** [comment] 2020-10-07 18:22
@mcarrano @mceledonia I added a couple of demos here https://patternfly-pr-3568.surge.sh/components/form/html-demos/

They're both the same form, but in the [2nd "modified" form](https://patternfly-pr-3568.surge.sh/components/form/html-demos/#modified), I've updated the select component and form select default text color (nothing is selected) to match the placeholder text color.

**Comment by mcarrano** [comment] 2020-10-07 18:45
In looking at these examples, it seems like the placeholder for the select is darker than the placeholder for the text field. Was that intentional @bgliwa01 ?

**Comment by bgliwa01** [comment] 2020-10-07 18:49
@mcarrano are you talking about in Michael's demos? if so, in the default or in the modified?

**Comment by mcarrano** [comment] 2020-10-07 20:46
Yes, in @mcoker 's demo. I believe that the 'modified' version was intended to show the effect of applying your styling change to the CSS.

**Comment by mcoker** [comment] 2020-10-07 21:06
@mcarrano sorry, the preview on surge wasn't working for some reason. I rebuilt it and it looks OK now. Do you mind looking again? https://patternfly-pr-3568.surge.sh/components/form/html-demos/

it should look like this

<img width="1270" alt="Screen Shot 2020-10-07 at 4 06 49 PM" src="https://user-images.githubusercontent.com/35148959/95387969-1fc56680-08b7-11eb-8bea-19b12227033d.png">

**Comment by mcarrano** [comment] 2020-10-08 17:49
That looks better @mcoker. But to my eye, the placeholder for the Select is still slightly darker that the placeholder for the type-ahead field above. What do you think @mceledonia ? Also looks like the "v" in the Select control is lighter.

![Screen Shot 2020-10-08 at 1 46 46 PM](https://user-images.githubusercontent.com/6619860/95495187-0d0d6900-096d-11eb-8093-62589afaa95f.png)

**Comment by bgliwa01** [comment] 2020-10-08 18:19
I see what you are saying now @mcarrano! good eye! It was not by design, I thought we were using black-600 for all of the text.

**Comment by mcoker** [comment] 2020-10-08 19:06
Ah thanks for calling that out. There is a bug in PF where the placeholder text color isn't being applied correctly. Should be fixed now - https://patternfly-pr-3568.surge.sh/components/form/html-demos/. Also updated the arrow color.

**Comment by mcoker** [comment] 2020-10-08 19:09
I also pushed a fix to align the form select's arrow with the others, you should see that in a few minutes when the build finishes. I'll also add a PR to fix that in PF.

**Comment by mcarrano** [comment] 2020-10-26 17:41
I have opened https://github.com/patternfly/patternfly/issues/3623 to move this along for core implementation.

**Closed** 2021-05-17 13:40 UTC
Labels: Epic, OpenShift, Update design doc
