### ISSUE TITLE
Broken image of Patternfly Symbol on the Modal demo

### ISSUE THREAD

**Issue by tadityar** [patternfly/patternfly-design#270] opened 2017-05-05 01:54 UTC
Page: http://www.patternfly.org/pattern-library/communication/about-modal/#/code
When you click 'Launch Modal' it will show a modal with a broken image of Patternfly Symbol on it.

![screenshot from 2017-05-05 09-49-16](https://cloud.githubusercontent.com/assets/7445868/25731413/bbb8d118-3178-11e7-8f9a-57893181de9e.png)

**Comment by suzannehillman** [comment] 2017-05-08 17:54
I'm wondering where the "logo-alt.svg" actually is located. That appears to be the issue.

This is also a problem on http://www.patternfly.org/pattern-library/application-framework/login-page/#/code

I bet it's a problem anywhere we have code looking for that icon. Or possibly any icon.

**Comment by suzannehillman** [comment] 2017-05-08 18:23
The correct location for this file is http://www.patternfly.org/assets/img/logo-alt.svg. 

It is not within the patternfly-design repo, but instead at https://github.com/patternfly/patternfly.github.io/blob/master/assets/img/logo-alt.svg. 

I don't think we can use relative URLs to include things from other patternfly repos. We might need some documentation around this, @LHinson?

**Comment by suzannehillman** [comment] 2017-05-08 18:35
I'm not at all sure which repositories the code is stored in, though. I'm wondering if this is part of the problem.

**Comment by suzannehillman** [comment] 2017-05-08 18:48
AngularJS looks to be in https://github.com/patternfly/angular-patternfly/blob/master/src/modals/about-modal.directive.js - I think changing that image src to the full URL would work for that part.

The HTML/CSS one might be in bits and pieces in the base patternfly repo? 

https://github.com/patternfly/patternfly/blob/master/tests/pages/_includes/widgets/communication/about-modal.html looks promising, and we'd need to change "{{site.baseurl}}" to either be accurate for this case, or make a new variable for the base URL of icons. I'm not sure where that is set, however, as I do not have this repo on my machine.

**Comment by michpetrov** [comment] 2017-05-09 09:02
@suzannehillman There are two kinds of issues:

I've filed patternfly/patternfly-org#393 for the angular part, the issue is that the angular demo has to work both as a standalone demo and as a part of the patternfly-org site (or so I assume). Changing the URL will not work unless the image is in the same location in both cases.

As for the regular part I think just changing the urls in [patternfly-org/source/_config.yml](https://github.com/patternfly/patternfly-org/blob/master/source/_config.yml) will work. The problem is caused by the site's `baseUrl` and I can't tell what it is supposed to be - on one hand the config says it's '', but when the site is generated it becomes '/' resulting in bad URLs.

**Comment by suzannehillman** [comment] 2017-05-12 20:35
@michpetrov Does the regular part belong in a base patternfly ticket? I'm still a little unclear how it works when a bug is entered against one repo but actually is related to a different one. I do not have the patternfly-org repo on my machine, and given that I'm not completely sure why the config settings are doing weird things, am not comfortable just making that change myself.

**Comment by michpetrov** [comment] 2017-05-15 14:16
@suzannehillman I don't know what the policy is either. I can fix it in patternfly-org providing that's where it should be fixed.

@bleathem could you clarify what is the expected value of `{{site.baseurl}}` in patternfly-org?
- If I run patternfly-org locally it's `/patternfly-org` resulting in `/patternfly-org//assets/img/logo-alt.svg` (which works despite the double slash)
- however on the live site the URL is `//assets/img/logo-alt.svg`, which doesn't work and the baseUrl is empty (which is currently impossible to set up via grunt)

**Comment by mcarrano** [comment] 2017-08-03 17:50
@LHinson are you familiar with this issue?  Looks like this is unrelated to the design and should be closed here, but wanted to check.

**Comment by LHinson** [comment] 2017-08-03 18:05
Looks like it's resolved now and that the icon is indeed showing. I'll close. Thanks @mcarrano!

**Closed by LHinson** 2017-08-03 18:05 UTC
Labels: bug
