### ISSUE TITLE
Visual inconsistencies with showing Filter Results on various patterns

### ISSUE THREAD

**Issue by beanh66** [patternfly/patternfly-design#474] opened 2017-10-26 22:01 UTC
### Bug: Visual inconsistencies with the Filter Results text 
* Results can either be shown as "X Results" or when filters are applied, the count, or "X of Y" is displayed. There is also "X of Y" selected for cases where multi select is enabled with checkboxes.
* We are inconsistent in how those results/ counts/ selections are displayed.
* These counts appear on the following patterns:
1. Pagination
2. Toolbar
3. Filter
4. Table View
5. List View
6. Card View

**Comment by beanh66** [comment] 2017-10-26 22:03
FYI @serenamarie125 @cshinn

**Comment by beanh66** [comment] 2017-10-26 22:16
Including examples below: 
<img width="1026" alt="screen shot 2017-10-26 at 6 03 40 pm" src="https://user-images.githubusercontent.com/18057044/32079434-9dea7892-ba78-11e7-9ec2-e9a769ab9d65.png">
<img width="1029" alt="screen shot 2017-10-26 at 6 03 50 pm" src="https://user-images.githubusercontent.com/18057044/32079435-9df662ba-ba78-11e7-984a-45bab00f01f3.png">
<img width="1027" alt="screen shot 2017-10-26 at 6 04 16 pm" src="https://user-images.githubusercontent.com/18057044/32079436-9dff9768-ba78-11e7-9b76-df0f32c39c5c.png">
<img width="1027" alt="screen shot 2017-10-26 at 6 04 27 pm" src="https://user-images.githubusercontent.com/18057044/32079437-9e0d4e12-ba78-11e7-8904-3a4f937776d9.png">
<img width="1027" alt="screen shot 2017-10-26 at 6 04 40 pm" src="https://user-images.githubusercontent.com/18057044/32079438-9e1a7362-ba78-11e7-859a-6971230473a8.png">
<img width="1036" alt="screen shot 2017-10-26 at 6 04 53 pm" src="https://user-images.githubusercontent.com/18057044/32079440-9e277e04-ba78-11e7-9784-7d075b2368ed.png">

**Comment by mcarrano** [comment] 2017-10-27 13:24
@beanh66 Thanks for filing this. I am aware that we have lots of inconsistency in this area. Since @cshinn is reworking the Filter pattern, I'd like to hold off on making immediate updates, but then we should definitely go back into each of these other patterns and make them consistent.

**Comment by beanh66** [comment] 2017-10-27 13:41
No problem @mcarrano, I figured that might be the case so I tagged @cshinn in case it overlaps with any of his work. It was something we ran into with Angular implementations and trying to get everything more consistent. I'm happy to revisit the issue following the filter updates and assist with any more changes as needed!

**Comment by catrobson** [comment] 2018-01-08 19:57
@cshinn @mcarrano any resolution on what direction we'd like this to head in?  It appears that this is still an issue, and I'm not clear on how to direct our patternfly-ng implementation of this.

**Comment by mcarrano** [comment] 2018-01-08 20:34
I think that the current direction should be what's specified in the revised Filter pattern here: http://www.patternfly.org/pattern-library/forms-and-controls/filter/#/design. Do you agree @cshinn ? The problem is that all of the views that use filtering have not been updated to reflect this design.

**Comment by catrobson** [comment] 2018-01-09 21:40
After reading that description, I am assuming that means that by default, when no filter is applied, the text would just say "xx items" - so we don't account for pagination and trying to say "currently showing xx of yy items" in this space.  This is fine with me, but just wanted to verify since I had to make that assumption rather than clearly know it from the text.

**Comment by mcarrano** [comment] 2018-01-09 21:44
That was my assumption, also, @catrobson . Can you confirm @cshinn ?

**Comment by cshinn** [comment] 2018-01-09 21:55
@catrobson @mcarrano yes, the current pattern does not address pagination or selected items. The filter results bar could either read "xx items", or if it makes more sense in the context, the bar could simply be removed

**Comment by mcarrano** [comment] 2018-08-30 16:05
We are going to address this as part of #576 so I will close this as a duplicate.

**Closed by mcarrano** 2018-08-30 16:05 UTC
Labels: Consistency, Duplicate, Medium
